CREATE DATABASE MARKETING_ANALYSIS;

USE MARKETING;

SELECT*FROM MARKETING;
SELECT DISTINCT(CAMPAIGNTYPE) FROM MARKETING;
SELECT DISTINCT(ADVERTISINGTOOL) FROM MARKETING;
ALTER TABLE MARKETING
DROP COLUMN ADVERTISINGPLATFORM,ADVERTISINGTOOL;
SELECT COUNT(*) FROM marketing;

SELECT GENDER FROM MARKETING
WHERE GENDER IS NULL;

SELECT AGE FROM MARKETING
WHERE AGE IS NULL;

SELECT * FROM MARKETING
WHERE INCOME IS NULL;

-- CHECK ALL NUMERICAL VALUES
--FOR NULLVALUE ASSIGN 1 OR 0
SELECT
SUM (CASE WHEN INCOME IS NULL THEN 1 ELSE 0 END)
FROM MARKETING;

SELECT
SUM (CASE WHEN INCOME IS NULL THEN 1 ELSE 0 END) AS NULL_INCOME,
SUM (CASE WHEN GENDER IS NULL THEN 1 ELSE 0 END) AS NULL_GENDER,
SUM (CASE WHEN AGE IS NULL THEN 1 ELSE 0 END) AS NULL_AGE,
SUM (CASE WHEN ADSPEND IS NULL THEN 1 ELSE 0 END) AS NULL_ADSPEND
FROM MARKETING;

--TYPE CASTING/TYPE CONVERSION
--CAST()

SELECT SUM(CAST(CONVERSION AS INT)) AS SUMCONV FROM MARKETING;
SELECT (SUM(CAST(CONVERSION AS INT))*100)/8000 FROM MARKETING;

--BEST CAMP CHANNEL FOR CONVERSION
SELECT CAMPAIGNCHANNEL,
(SUM(CAST(CONVERSION AS INT))*100.00) /COUNT(*) AS CONVERSIONRATE
FROM MARKETING
GROUP BY CAMPAIGNCHANNEL
ORDER BY CONVERSIONRATE DESC;

SELECT CAMPAIGNTYPE,
(SUM(CAST(CONVERSION AS INT))*100.00) /COUNT(*) AS CONVERSIONRATE
FROM MARKETING
GROUP BY CAMPAIGNTYPE
ORDER BY CONVERSIONRATE DESC;
--GENDER WISE
SELECT GENDER,CAMPAIGNCHANNEL,
(SUM(CAST(CONVERSION AS INT))*100.00) /COUNT(*) AS CONVERSIONRATE
FROM MARKETING
GROUP BY CAMPAIGNCHANNEL,GENDER
ORDER BY CONVERSIONRATE DESC;

SELECT INCOME FROM MARKETING;

--CREATE INCOME GRP COL BASED ON CERTAIN CONDN
SELECT MAX(INCOME) AS MAXINCOME;
MIN(INCOME) AS MININCOME FROM MARKETING;

ALTER TABLE MARKETING
ADD INCOMEGROUP VARCHAR(500);
SELECT INCOMEGROUP FROM MARKETING;

SELECT INCOME,
CASE
WHEN INCOME >100000 THEN 'HIGH INCOME'
WHEN INCOME <50000 THEN 'LOW INCOME'
ELSE 'AVERAGE'
END
FROM MARKETING;

SELECT*FROM MARKETING;

ALTER TABLE MARKETING ADD INCOMEGROUP VARCHAR(500);

UPDATE MARKETING 
SET INCOMEGROUP=
CASE
WHEN INCOME >100000 THEN 'HIGH INCOME'
WHEN INCOME <50000 THEN 'LOW INCOME'
ELSE 'AVERAGE'
END;
SELECT*FROM MARKETING;

ALTER TABLE MARKETING ADD ADSPENDGROUP VARCHAR(500);

SELECT ADSPEND,
CASE
WHEN ADSPEND <2000 THEN 'LOW spend'
WHEN adspend >2000 AND ADSPEND <6000 THEN 'MEDIUM spend'
ELSE 'HIGH SPEND'
END FROM MARKETING;

UPDATE MARKETING 
SET ADSPENDGROUP=
CASE
WHEN ADSPEND <2000 THEN 'LOW spend'
WHEN adspend >2000 AND ADSPEND <6000 THEN 'MEDIUM spend'
ELSE 'HIGH SPEND'
END;

SELECT*FROM MARKETING;

SELECT ADSPENDGROUP,
ROUND (SUM(CAST(CONVERSION AS INT))*100,2) /COUNT(*) AS CONVERSIONRATE
FROM MARKETING
GROUP BY ADSPENDGROUP
ORDER BY CONVERSIONRATE DESC;





